In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
data = pd.read_excel("./resources/Charting.xlsx")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498 entries, 0 to 2497
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             2498 non-null   datetime64[ns]
 1   S&P 500 - Close  2498 non-null   float64
 2   Open             2498 non-null   float64
 3   High             2498 non-null   float64
 4   Low              2498 non-null   float64
 5   Volume           2498 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 117.2 KB

In [20]:
data["Date"] = pd.to_datetime(data["Date"])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498 entries, 0 to 2497
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             2498 non-null   datetime64[ns]
 1   S&P 500 - Close  2498 non-null   float64
 2   Open             2498 non-null   float64
 3   High             2498 non-null   float64
 4   Low              2498 non-null   float64
 5   Volume           2498 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 117.2 KB

In [21]:
data["ReturnsOverNight"] = data["Open"].shift(-1) / data["S&P 500 - Close"] - 1
data["ReturnsDay"] = data["S&P 500 - Close"] / data["Open"] - 1

df = data

df["A_ReturnsOverNight"] = df["ReturnsOverNight"].cumsum()
df["A_ReturnsDay"] = df["ReturnsDay"].cumsum()

df.drop(df.index[-1], inplace=True)
df.tail(2)

,Date,S&P 500 - Close,Open,High,Low,Volume,ReturnsOverNight,ReturnsDay,A_ReturnsOverNight,A_ReturnsDay
2495,2025-04-02,5670.97,5580.76,5695.31,5571.48,2792812,-0.031428,0.016164,0.707736,0.390705
2496,2025-04-03,5396.52,5492.74,5499.53,5390.83,5016396,-0.019342,-0.017518,0.688394,0.373187

In [26]:
df.describe().iloc[1:,-4:]*100

      ReturnsOverNight  ReturnsDay  A_ReturnsOverNight  A_ReturnsDay
mean          0.027569    0.014945           34.154372     17.330066
min          -7.466931   -5.709920           -0.063772    -13.494258
25%          -0.148426   -0.332195           10.638948      8.735647
50%           0.038392    0.045641           31.172132     15.007959
75%           0.228085    0.455915           54.525206     27.290841
max           4.784124    5.487570           80.849643     44.334528
std           0.518389    0.882783           24.003293     13.264039